/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as CuttingPlanRouteImport } from './pages/cutting-plan'
import { Route as IndexRouteImport } from './pages/index'

const CuttingPlanRoute = CuttingPlanRouteImport.update({
  id: '/cutting-plan',
  path: '/cutting-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cutting-plan': typeof CuttingPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cutting-plan': typeof CuttingPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cutting-plan': typeof CuttingPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cutting-plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cutting-plan'
  id: '__root__' | '/' | '/cutting-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuttingPlanRoute: typeof CuttingPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cutting-plan': {
      id: '/cutting-plan'
      path: '/cutting-plan'
      fullPath: '/cutting-plan'
      preLoaderRoute: typeof CuttingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuttingPlanRoute: CuttingPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
